GET http://localhost:3000/proxy/?number=&enumeration_type=NPI-1&first_name=John&state=NY&limit=10&pretty=on

###
GET https://npiregistry.cms.hhs.gov/api/?number=&enumeration_type=NPI-1&first_name=John&state=NY&limit=10&pretty=on&version=2.1

###
GET https://npiregistry.cms.hhs.gov/api/?number=&enumeration_type=NPI-1&city=Rockville&state=MD&pretty=on&version=2.1

###

GET https://maps.googleapis.com/maps/api/place/findplacefromtext/json?key=AIzaSyBFGv9-hlOIkwuDIwBDBinQVyiKDsFBnrc&inputtype=textquery&fields=place_id,rating,user_ratings_total&input=dmitry%20malkin

###
GET https://maps.googleapis.com/maps/api/place/details/json?key=AIzaSyBFGv9-hlOIkwuDIwBDBinQVyiKDsFBnrc&place_id=ChIJtY_9lWFYwokRFRUrwJpWr6c&fields=rating,review,user_ratings_total,website
